version: '3.8'

services:
  api:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    container_name: lil_kakish_devchallenge_21  # Replace 'your_id' with your unique identifier
